# Header
menu:
  首页: /

# Content
excerpt_link: 进来看看
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.ico
